html-block-and-inline - Marvin Loreto
marvinloreto/rc-1222-code-solutions pull request #3
Opened 2022-12-05 23:12 UTC by marvinloreto

![Screenshot (98)](https://user-images.githubusercontent.com/117399643/205763157-50cf23e6-cb86-4617-8af9-82661ddb48f8.png)

2022-12-05 23:22 UTC, JenBowman1 requested changes
Hey Marvin, this looks good! Just a couple small changes, please use the "em" tag instead of the "i" tag, and the "strong" tag instead of the "b" tag.

2022-12-05 23:35 UTC, marvinloreto commented
![Screenshot (100)](https://user-images.githubusercontent.com/117399643/205767736-3dc312bb-9e16-4a9b-ab4b-085a1e5b9d8a.png)

2022-12-06 00:00 UTC, JenBowman1 approved these changes

2022-12-06 00:02 UTC, JenBowman1 approved these changes
👍

2022-12-06 00:16 UTC, merged