express-notes-api - Marvin Loreto
marvinloreto/rc-1222-code-solutions pull request #87
Opened 2023-01-27 21:42 UTC by marvinloreto

![GET_all](https://user-images.githubusercontent.com/117399643/215205996-743f5d92-4ffc-442d-a1d1-f12623d3eaf1.png)
![GET_all_status](https://user-images.githubusercontent.com/117399643/215206007-7a5d86b3-1df3-41e2-8ecd-f4c26f7d8679.png)
![POST_all_status](https://user-images.githubusercontent.com/117399643/215206019-9322b8f5-3e85-43e3-a1c3-dcdf7ac5c389.png)
![Post_err_500](https://user-images.githubusercontent.com/117399643/215206027-156fab69-d117-49fe-8577-0b524bf29202.png)
![DELETE_all_status](https://user-images.githubusercontent.com/117399643/215206042-18da7a08-cffa-4a51-bc4e-b75c76a73e09.png)
![Delete_err_500](https://user-images.githubusercontent.com/117399643/215206048-8ef2c3f6-87ca-49ee-9b08-e22b8f31737d.png)
![PUT_all_](https://user-images.githubusercontent.com/117399643/215206056-4b8a0def-27b3-4324-835b-e760218b3cea.png)
![Put_err_500](https://user-images.githubusercontent.com/117399643/215206062-d9c7f4ee-5256-4a1d-9520-41edfdf23881.png)

2023-01-29 17:50 UTC, Zhiwutian requested changes
Great work Marvin! Let me know if you have any questions on the feedback!

2023-01-29 17:50 UTC, Zhiwutian commented on express-notes-api/index.js
> +  const id = req.params.id;
I would use the `Number` constructor here, to convert the string value to a number

2023-01-29 17:50 UTC, Zhiwutian commented on express-notes-api/index.js
> +  if (id < 1) {
you want to check specifically if id isNaN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

You also want to confirm the number is an integer value: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

2023-01-29 17:50 UTC, Zhiwutian commented on express-notes-api/index.js
> +  if (id < 1) {
same as above, expand the check for isInteger and IsNaN for the id

2023-01-29 17:50 UTC, Zhiwutian commented on express-notes-api/index.js
> +  if (id < 1) {
same as above with the Number checks for is integer and is nan after converting the id to a Number

2023-01-30 00:01 UTC, marvinloreto commented
![Screenshot (247)](https://user-images.githubusercontent.com/117399643/215363615-7ed36e1a-c64b-4e64-ac74-21d67b9ef06c.png)
![Screenshot (246)](https://user-images.githubusercontent.com/117399643/215363619-a22c4d18-44b5-442d-9776-e903a3905fc5.png)
![Screenshot (244)](https://user-images.githubusercontent.com/117399643/215363621-89945d07-6989-41b6-8b76-557af06f94cc.png)

2023-01-30 16:32 UTC, Zhiwutian approved these changes
👍🏼

2023-01-30 17:44 UTC, merged